on: [push, pull_request]

name: R-CMD-check

jobs:

  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: R-CMD-check
   steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install libcurl4-openssl-dev
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Install heroku cli
        run: sudo snap install --classic heroku
      - name: building dockerfile
        run: Rscript -e 'golem::add_dockerfile_heroku(from = "rocker/r-ver:latest")' && docker build -t punkapi .
      - name: pushing dockerfile
        run: |
          heroku container:login
          heroku create punkapi-0-0-0-9000
          heroku container:push web --app punkapi-0-0-0-9000
          heroku container:release web --app punkapi-0-0-0-9000
          heroku open --app punkapi-0-0-0-9000
